baseURL = "https://hhi-wasit.github.io/websiteSource-master/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = "en-us"
title = "Ahmed Azeez | Academic Website"
theme = "data-science"
disqusShortname = ""
enableEmoji = true
enableRobotsTXT = true
preserveTaxonomyNames = true

[permalinks]
    post = "/:year/:month/:day/:slug/"
[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
[params]
  author = "Ahmed Azeez"
  description = "Academic website of Ahmed Azeez, a public health researcher and lecturer specialising in infectious disease epidemiology, surveillance, modelling, biostatistics, and instrument development."
  orcid = "https://orcid.org/0000-0002-9004-9689"
  website = "https://ahmed-azeez.github.io/"
  images = ['introImage-light.png']
  highlight = true
  highlightjsVersion = "9.15.6"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml", "javascript"]
  custom = true
  highlightjsThemeLight = ""
  highlightjsThemeDark = ""
[params.social]
  email = "mailto:ahmed.azeez1987@gmail.com"
  twitter = ""
  github = ""
  linkedin = ""
  stackoverflow = ""
  facebook = ""
  instagram = ""
  dribbble = ""
  kaggle = ""
  medium = ""
  patreon = ""
  pinterest = ""
  youtube = ""
