# theme.toml template for a Hugo theme
# See https://gohugo.io/hugo-modules/theme-components/ for theme metadata guidance

name = "Blogfolio Bricks"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "A responsive academic portfolio and blog theme with light and dark modes."
homepage = "https://ahmed-azeez.github.io/"
tags = ["blog", "responsive", "portfolio", "dark", "light", "contact form", "Highlight.js"]
features = []
min_version = "0.38"

[author]
  name = "Ahmed Azeez Hasan, PhD"
  homepage = "https://ahmed-azeez.github.io/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
